
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NiA
 */
public class Form6 extends javax.swing.JFrame {

    /**
     * Creates new form Form6
     */
    Timer t,update;
    int time=0;
    public Form6() {
        initComponents();
        groupButton();
        try{
            Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/General_knowledge_quiz", "Isha", "Isha");
            String query="select Question_Id, Question from Isha.Easy_Questions where Question_Id=5";
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery(query);
            //ResultSet rs=stmt.executeQuery("select Question_Id, Question from Isha.Easy_Questions where Question_Id=1");
            rs.next();
          
                  int i=rs.getInt("Question_Id");
                  String ques=rs.getString("Question");
                  jLabel1.setText(i+""+ques);
                  //jTextField1.getText();
          
                  stmt.close();
                  con.close();
        }catch(Exception e){}
        correct.setText("correct answers : "+evaluate.count);
        t=new Timer(10000,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Form7 f=new Form7();
                f.setVisible(true);
                Form6.this.dispose();
                ((Timer)e.getSource()).stop();
                
            }
        });
        update=new Timer(1000,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                timer.setText(""+time++);
            }
        });
        t.start();
        update.start();
    }
     public void groupButton()
    {
        ButtonGroup bg1=new ButtonGroup();
        bg1.add(jRadioButton1);
        bg1.add(jRadioButton2);
        bg1.add(jRadioButton3);
        bg1.add(jRadioButton4);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        correct = new javax.swing.JLabel();
        timer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jRadioButton1.setText("Delhi");

        jRadioButton2.setText("Chandigarh");

        jRadioButton3.setText("Deradun");

        jRadioButton4.setText("Mumbai");

        jButton1.setText("submit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        correct.setText("jLabel2");

        timer.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(timer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 39, Short.MAX_VALUE)
                        .addComponent(correct, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(timer))
                .addGap(38, 38, 38)
                .addComponent(jRadioButton1)
                .addGap(32, 32, 32)
                .addComponent(jRadioButton2)
                .addGap(34, 34, 34)
                .addComponent(jRadioButton3)
                .addGap(39, 39, 39)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(correct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String radioText="";
        if(jRadioButton1.isSelected()){
            radioText=jRadioButton1.getText();
        }
        if(jRadioButton2.isSelected()){
            radioText=jRadioButton2.getText();
        }
        if(jRadioButton3.isSelected()){
            radioText=jRadioButton3.getText();
        }
        if(jRadioButton4.isSelected()){
            radioText=jRadioButton4.getText();
        }
        
        try{
            
            Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/General_knowledge_quiz", "Isha", "Isha");
            String query="select Answer from Isha.Easy_Questions where Question_Id=5";
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery(query);
            //ResultSet rs=stmt.executeQuery("select Question_Id, Question from Isha.Easy_Questions where Question_Id=1");
            rs.next();
                  String ans=rs.getString("Answer");
                  if(radioText==ans)
                  {
                      evaluate.count=evaluate.count+1;
                      System.out.println(evaluate.count);
                  }
                  Form7 f=new Form7();
                  f.setVisible(true);
                  this.dispose();
                  stmt.close();
                  con.close();
        }catch(Exception e){}
        this.dispose();
                   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel correct;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JLabel timer;
    // End of variables declaration//GEN-END:variables
}
